spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management_system
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/**.xml
#日志文件配置路径
logging:
  level:
    com: debug

ms:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    adminSecretKey: psl
    # 设置jwt过期时间
    adminTtl: 7200000
    # 设置前端传递过来的令牌名称
    adminTokenName: token