server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      # 用于服务间的通信
      server-addr: localhost:8848 # nacos地址
      discovery: # 用于发现服务
        server-addr: localhost:8848 # nacos地址
    gateway:
#      discovery:
#        locator:
#          enabled: true #是否开启
#          lower-case-service-id: true #id使用小写
      routes:
        - id: project
          uri: lb://project
          predicates:
            - Path= /project/**
        - id: comment
          uri: lb://comment
          predicates:
            - Path= /comment/**
        - id: document
          uri: lb://document
          predicates:
            - Path= /document/**
        - id: task
          uri: lb://task
          predicates:
            - Path= /task/**
        - id: team
          uri: lb://team
          predicates:
            - Path= /team/**
        - id: user
          uri: lb://user
          predicates:
            - Path= /user/**
      default-filters:
        - AddRequestHeader=Truth,666 wotaiqiangla
        - AddRequestHeader=wg,gateway
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options的请求拦截
        cors-configurations:
          '[/**]':
            # 后端之间的http请求不需要配置，只需配置ajax请求
            allowedOrigins: # 允许哪些网站跨域
              - "http://localhost:8080"
              - "http://10.148.31.18:8080"
            allowed-methods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowed-headers: # 允许请求头中的哪些信息
              - "*"
            allowCredentials: true # 允许携带cookie
            maxAge: 360000 # 在该时间段内，不在询问是否允许

