server:
  port: 8090
  servlet:
    context-path: /project
#微服务配置
spring:
  application:
    name: project
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
      discovery:
        server-addr: localhost:8848
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management_system
    username: root
    password: 123456
#日志文件配置路径
logging:
  level:
    com:
      api: debug
#Swagger
#springdoc相关配置
springdoc:
  swagger-ui:
    #自定义swagger前端请求路径，输入http：127.0.0.1:8080/swagger-ui.html会自动重定向到swagger页面
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs    #swagger后端请求地址
    enabled: true   #是否开启文档功能
  group-configs:
    - group: 'com.project'
      paths-to-match: '/**'
      packages-to-scan: com.project   #按包路径匹配:一般到启动类的包名
#knife4j相关配置 可以不用改
knife4j:
  enable: true    #开启knife4j，无需添加@EnableKnife4j注解
  setting:
    language: zh-CN   #中文
    swagger-model-name: 实体类   #重命名SwaggerModel名称,默认
  #开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: psl
    # Basic认证密码
    password: psl123