server:
  port: 8095
  servlet:
    context-path: /user
#微服务配置
spring:
  application:
    name: user
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
      discovery:
        server-addr: localhost:8848
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management_system
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
  #一般使用SMTP服务器 简单邮件传输协议进行发送邮件
  mail:
    host: smtp.qq.com
    port: 465
    #发送邮件的邮箱地址：改成自己的邮箱
    username: 2370453803@qq.com
    #发送短信后它给你的授权码 填写到这里
    password: fjqjdkzljcxgdjgd
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
#日志文件配置路径
logging:
  level:
    com: debug
#Swagger
#springdoc相关配置
springdoc:
  swagger-ui:
    #自定义swagger前端请求路径，输入http：127.0.0.1:8080/swagger-ui.html会自动重定向到swagger页面
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs    #swagger后端请求地址
    enabled: true   #是否开启文档功能
  group-configs:
    - group: 'com.user'
      paths-to-match: '/**'
      packages-to-scan: com.user   #按包路径匹配:一般到启动类的包名
#knife4j相关配置 可以不用改
knife4j:
  enable: true    #开启knife4j，无需添加@EnableKnife4j注解
  setting:
    language: zh-CN   #中文
    swagger-model-name: 实体类   #重命名SwaggerModel名称,默认
  #开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: psl
    # Basic认证密码
    password: psl123

ms:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    adminSecretKey: psl
    # 设置jwt过期时间
    adminTtl: 7200000
    # 设置前端传递过来的令牌名称
    adminTokenName: token

