server:
  port: 8092
  servlet:
    context-path: /document
minio:
#  todo 配置minio的地址和端口
  endpoint: http://127.0.0.1:9005
  accessKey: F4VJ7SEYvDvg8wH5kidA
  secretKey: nOcyCTT5aQjTbYUeAnnkd3bQ4JX61pwlOsJKcRoM
  bucketName: ms-admin
  secure: false
#微服务配置
spring:
  application:
    name: document
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
      discovery:
        server-addr: localhost:8848
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management_system
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      database: 5
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

#日志文件配置路径
logging:
  level:
    com: info
    com.baomidou.mybatisplus.core.mapper: debug
#Swagger
#springdoc相关配置
springdoc:
  swagger-ui:
    #自定义swagger前端请求路径，输入http：127.0.0.1:8080/swagger-ui.html会自动重定向到swagger页面
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs    #swagger后端请求地址
    enabled: true   #是否开启文档功能
  group-configs:
    - group: 'com.document'
      paths-to-match: '/**'
      packages-to-scan: com.document   #按包路径匹配:一般到启动类的包名
#knife4j相关配置 可以不用改
knife4j:
  enable: true    #开启knife4j，无需添加@EnableKnife4j注解
  setting:
    language: zh-CN   #中文
    swagger-model-name: 实体类   #重命名SwaggerModel名称,默认
  #开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: psl
    # Basic认证密码
    password: psl123

ms:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    adminSecretKey: psl
    # 设置jwt过期时间
    adminTtl: 7200000
    # 设置前端传递过来的令牌名称
    adminTokenName: token